INSERT INTO roles (role_name)
  VALUES ('admin'),
        ('moniter'),
        ('user');

INSERT INTO users ( email, password, first_name, last_name, dob, register_date, last_login, total_login,contact, user_role)
  VALUES ( 'admin@gmail.com', '$2b$12$cD49ljQk6rRfRpZCaW8fcuXlnLd3htita58y/.G6RLPpNj4RbFyUW', 'Admin', 'AdminLast', '1990-02-02','2020-04-03', '2020-11-20', 34,True, 1),
        ( 'user1@gmail.com','$2b$12$U5zM7N276dItYH8BCfKVSu5ok1hqqfjPNukYCC6eu31bbOjykCFRi', 'UserOne','UserOneLast', '2000-01-01','2020-04-03', '2020-10-01', 13,True, 3),
        ( 'user2@gmail.com','$2b$12$ZrCkYXWrN8TE5a/Wy8qnp.Bhhv8YJe95.g9b2LRWjq4UhdEo3iPou' , 'UserTwo','UserTwoLast', '2000-01-02','2020-04-03', '2020-10-02', 10,True, 3),
        ( 'user3@gmail.com', '$2b$12$bEZlbWiUimaO5ewTDU2mrOMOlBtr8CoTDJjVXv7u2ksPvlHsUEzhq', 'UserThree','UserThreeLast', '1999-03-02','2020-05-03', '2020-10-12', 9,True, 3),
        ( 'user4@gmail.com', '$2b$12$QRDJ5bnMTuS3HT601kuHRucXC08XhiXpMUAtB..ILi8P9dBGks87e', 'UserFour','UserFourLast', '2002-04-12', '2020-05-03','2020-10-23', 20,True, 3),
        ( 'user5@gmail.com', '$2b$12$lzXfkBZSyKfdf/HAnfcWPuTzSuCj1JsUuYoYhMD9m4zwMY/RQSbPC' , 'UserFive','UserFiveLast', '2004-11-12','2020-05-03', '2020-11-17', 5,True, 3),
        ( 'user6@gmail.com', '$2b$12$kxxcsLUTGuCLWs7VyCnvSORDNTd83J.UCnpX8./U8M5qUJ.pjeu1m' , 'UserSix','UserSixLast', '1998-12-22', '2020-05-03', '2020-11-13', 4,True, 3),
        ( 'user7@gmail.com', '$2b$12$AKMIAyIjykP5n/IFd2upPeLFYl24epbFWvY1/gz1pg3aJu3hWnRq6', 'UserSeven','UserSevenLast', '2000-06-22', '2020-05-13','2020-04-20', 30,False, 3),
        ( 'user8@gmail.com', '$2b$12$Xap3StJKXA/AZjK4E9qx2uE2eCpdwy3MaJufRlLcnf3JksjxXAVTq' , 'UserEight','UserEightLast', '1984-12-25','2020-05-13', '2020-10-30', 21,False, 3),
        ( 'user9@gmail.com', '$2b$12$mOvlBJFCIMSEc.PZT.qTTOYvVQiFb67hyAZ1/2FNy4hZBTifCinzy', 'UserNine','UserNineLast', '1985-12-24', '2020-05-13','2020-10-31', 22,False, 3),
        ( 'user10@gmail.com', '$2b$12$7wY6IAg6160cua9dUBE/kejiavErOWdpe03vaNs1zJBoi0WQcllXS', 'UserTen','UserTenLast', '1986-12-25','2020-05-13', '2020-11-10', 27,False, 3),
        ( 'user11@gmail.com', '$2b$12$XLPvKyMmVJZNT0cZIwQqb.s.PksnS.MmemvDntbkgYasnNZ9xLBcW', 'UserEleven','UserElevenLast', '1984-12-02', '2020-06-13','2020-11-10', 6,False, 3),
        ( 'user12@gmail.com', '$2b$12$KXF6KbGqKeSF7W78.eXLWu1swCjdBE/LFVjF8TS695tPrwW5Bjp96', 'UserTwelve','UserTwelveLast', '1998-02-25', '2020-06-13','2020-11-03', 17,False, 3),
        ( 'user13@gmail.com', '$2b$12$PZXmYqZKhZsJR.XYbZjNN.J8dZosiIMDFacZ4o6A0Mm1xmJc190o2', 'UserThirteen','UserThirteenLast', '1999-02-25','2020-06-13', '2020-09-30', 5,False, 3),
        ( 'user14@gmail.com', '$2b$12$TdoTRk26SNLyV4yEKkuFAu7R3TanJuyngFkfyn7AUf6ZkezlDiPBu', 'UserFourteen','UserFourteenLast', '1984-12-13','2020-06-13', '2020-09-30', 13,True, 3),
        ( 'user15@gmail.com', '$2b$12$cAYMPDgbS.zVozZb7fwnG.aY9DZKLrzXuFaoPkVXNDK3rvZDoCkYi', 'UserFifteen','UserFifteenLast', '1980-03-20','2020-06-13', '2020-09-30', 1,True, 3),
        ( 'user16@gmail.com', '$2b$12$snDod6km7aGTtkilC7CncudhZSoEyWG4Upz8kCmwmnOqXa2nbG3ma', 'UserSixteen','UserSixteenLast', '1999-05-02','2020-06-13', '2020-11-13', 15,True, 3);

INSERT INTO shakes (name, shake_group, description, suggestions, available)
  VALUES ('bahama breeze',1, 'pineapple, ornage, coconut', '', True),
        ('berry blast',1, 'strawberry, raspberry, blueberry', '', True),
        ('hawaiian luau', 1, 'tropical pineapple coconut and vanilla', '', True),
        ('island surprise', 1, 'berry and coconut', '',True),
        ('orange julious', 1 , 'tastes like orange', '', True),
        ('orange creamsickle', 1, 'orange and cream', '', True),
        ('pineapple fusion', 1, 'pineapple and vanilla','', True),
        ('strawbwerry banana', 1, 'strawberry and banana', '', True),
        ('strawberry orange', 1, 'strawberry and orange', '', True),
        ('banana', 1,'banana','', True ),
        ('caramel cafe late', 2, 'caramel, coffee and crem', '', True),
        ('chocolate caramel cappuchino',2, 'chocolate with caramel and coffee', '', True),
        ('coffee heath bar crunch', 2, '', '', True),
        ('coffee smores', 2, '', '', True),
        ('french vanilla cappuchino', 2, '', '', True),
        ('mocha cappuchino', 2, '', '', True),
        ('peppermint mocha', 2, 'coffee, chocolate, pepermint, vanilla', '', True),
        ('snickers coffee', 2,'','', True),
        ('apple pie', 3, 'apple, cinnamon, and vanilla','', True),
        ('banana caramel cheesecake', 3, '','', True),
        ('coconut creme pie', 3, 'coconut, vanilla, and grahm cracker','', True),
        ('banana cream pie', 3, 'banana, grahm crackers and vanilla','', True),
        ('banana wafer', 3, '','', True),
        ('cannoli chip', 3, '','', True),
        ('cinnabon', 3, '','', True),
        ('cinnabon crumb cake',3,'','', True),
        ('chocolate caramel cheeseckae', 3,'','', True),
        ('german chocolate cake',3, '','', True),
        ('kandy kake', 3, '','', True),
        ('key lime pie', 3, '','', True),
        ('strawberry shortcake', 3, '','', True),
        ('andes mint', 4, '','', True),
        ('butterfinger', 4, '','', True),
        ('buckeye', 4, '','', True),
        ('cookie monster', 4, '','', True),
        ('heath bar crunch', 4, '','', True),
        ('milky way', 4, '','', True),
        ('nutter butter', 4, '','', True),
        ('peanut butter', 4, '','', True),
        ('cookie', 4,'','', True),
        ('rice crispy treat', 4, '','', True),
        ('samoa', 4, '','', True),
        ('snickers', 4, '','', True),
        ('twix', 4, '','', True),
        ('white chocolate', 4, '','', True),
        ('reeses', 4, '','', True),
        ('butter beer', 5, '','', True),
        ('blondie', 5, '','',True),
        ('butter pecan', 5, '','', True),
        ('chunky monkey', 5, '','', True),
        ('churro', 5, '','', True),
        ('peanut butter banana', 5, '','', True),
        ('chocolate', 5, '','', True),
        ('vanilla', 5,'','', True),
        ('fluffer nutter', 5, '','', True),
        ('chocolate coverd strawberry', 5, '','', True),
        ('intense chocolate orange', 5, '','', True),
        ('praline blondie', 5, '','', True),
        ('praline dream', 5, '','', True),
        ('shamrock', 5, '','', True),
        ('snickers ice cream', 5, '','', True),
        ('vanilla butterfinger', 5, '','', True),
        ('captain america',6,'pomegranate lift off, raspberry tea, aloe, raimbow candy amd blue blast','',True),
        ('fruity gusher', 6, 'pomegranate lift off, raspberry tea, aloe, blue bast and grape', '', True),
        ('gummy bear', 6, 'lemon/lime lift off, lemon tea, aloe, strawberry and watermelon', '', True),
        ('house special', 6, 'orange lift off, original tea, aloe, rainbow candy top', '', True),
        ('jolly rancher', 6, 'lemon/lome lift off, sour apple, original tea, aloe and watermelon', '', True),
        ('ocean wave', 6, 'lemon/lime lift off, original tea, aloe, blue blast and blue raspberry', '', True),
        ('rainbow candy', 6, 'pomegranate lift off, raspberry tea, rainbow, aloe, sour apple layer and blue blast', '', True),
        ('skittals', 6, 'orange lift off, grape, original tea, aloe and cherry', '', True),
        ('strawberry lemonade', 6, 'pomegranate lift off, original tea, strawberry, aloe, and lemonade', '', True),
        ('summer breeze', 6, 'orange lift off, raspberry tea, aloe, pineapple and cherry', '', True),
        ('the joker', 6, 'lime lift off, original tea, aloe, sour apple and grape', '', True),
        ('house blend', 7,'','', True),
        ('mocha', 7, '','', True),
        ('almond', 7, '','', True),
        ('caramel',7, '','', True),
        ('coconut', 7, '','', True),
        ('hazelnut', 7, '','', True),
        ('pumpkin', 7, '', '', True),
        ('peppermint', 7, '','', True),
        ('peppermint mocha', 7, '','', True),
        ('salted caramel', 7, '','', True),
        ('toasted marshmallow', 7, '','', True),
        ('vanilla', 7, '','', True),
        ('birthday cake', 11, '','', True),
        ('brownie batter', 11, '','', True),
        ('banana nut muffin', 11, '','', True),
        ('cinnamon toast crunch', 11,'','',True),
        ('fruity pebbles',11,'','', True),
        ('lemon pound cake', 11, '','', True),
        ('mint chocolate chip',3,'','',True),
        ('moose tracks', 11, '','', True),
        ('oatmeal cookie', 11, '', '', True),
        ('oreo', 11, '', '', True),
        ('peanut butter pie', 11, '','', True),
        ('reeses cup', 11, '','', True),
        ('smores', 11, '','', True),
        ('white chocolate raspberry cheesecake', 11, '','', True),
        ('vanilla salted caramel crunch', 11, '','', True),
        ('tripple chocolate caramel cheesecake', 11, '','', True),
        ('cinnamon swirl', 8, '','', False),
        ('banana nut muffin', 8, '','', True),
        ('oatmeal cookie', 8, '', '', True),
        ('peanut butter banana', 8, '','', True),
        ('fall festival', 9, '','', False),
        ('caramel harvest', 9, '','', False),
        ('chocolate valentine', 9, '','', False),
        ('cadbury caramel egg',9, '','', False),
        ('chocolate candy cane', 9, '','', False),
        ('gingerbread house', 9, '','', False),
        ('maple pecan crunch', 9, '','', True),
        ('chocolate maple pecan', 9, '','', True),
        ('butter pecan', 9, '','', True),
        ('maple pecan ice cream', 9, '', '', True),
        ('maple pecan pancake', 9, '', '', True),
        ('maple pecan chip', 9, '','', True),
        ('maple pecan cheesecake', 9, '','', True),
        ('maple pecan pie', 9, '','', True),
        ('chocolate peanut butter truffle', 9, '', '', True),
        ('strawberry cheesecake', 9, '','', True),
        ('red velvet cake', 9, '','', True),
        ('chocolate coverd strawberry', 9, '','', True),
        ('raspberry lemon tart',9, '','', True),
        ('beauty and the beast', 10,  '', '',True),
        ('cupids crush', 10,  '', '',True),
        ('love postion no 9', 10,  '', '',True);

INSERT INTO has_had (user_id, shake_id, rating, comment, this_shake)
  VALUES (2, 0001, 4, 'delicious',3),
        (2, 0002, 3, 'okay, i enjoyed it',2),
        (2, 0003, 2, 'okay',1),
        (2, 0005, 3, 'okay',2),
        (2, 0007, 2, 'okay',1),
        (2, 0009, 5, 'favorite of them all',7),
        (2, 0010, 2, 'okay',1),
        (2, 0013, 4, 'delicious',4),
        (2, 0015, 2, 'okay',1),
        (3, 0010, 3, 'okay',2),
        (3, 0008, 2, 'okay',1),
        (3, 0002, 3, 'okay',2),
        (3, 0015, 2, 'okay',1),
        (3, 0007, 5, 'favorite',7),
        (3, 0005, 2, 'okay',1),
        (3, 0004, 4, 'delicious',4),
        (3, 0001, 2, 'okay',1),
        (4, 0010, 3, 'okay',2),
        (4, 0005, 2, 'okay',1),
        (4, 0012, 3, 'okay',2),
        (4, 0015, 2, 'okay',1),
        (4, 0007, 5, 'favorite',7),
        (4, 0005, 2, 'okay',1),
        (4, 0002, 4, 'delicious',4),
        (4, 0009, 2, 'okay',1),
        (5, 0013, 2, 'okay',1),
        (5, 0002, 3, 'okay',2),
        (5, 0003, 2, 'okay',1),
        (5, 0010, 3, 'okay',2),
        (5, 0001, 2, 'okay',1),
        (5, 0004, 3, 'okay',2),
        (5, 0007, 2, 'okay',1),
        (5, 0011, 3, 'okay',2),
        (5, 0016, 2, 'okay',1),
        (6, 0002, 3, 'okay',2),
        (6, 0003, 3, 'okay',1),
        (6, 0005, 2, 'okay',2),
        (6, 0007, 3, 'okay',1),
        (6, 0009, 5, 'favorite',7),
        (6, 0010, 1, 'okay',1),
        (6, 0013, 4, 'delicious',4),
        (6, 0003, 3, 'okay',1),
        (7, 0010, 3, 'okay',2),
        (7, 0008, 2, 'okay',1),
        (7, 0002, 3, 'okay',2),
        (7, 0015, 2, 'okay',1),
        (7, 0007, 5, 'favorite',7),
        (7, 0005, 2, 'okay',1),
        (7, 0004, 4, 'delicious',4),
        (7, 0001, 2, 'okay',1),
        (8, 0010, 3, 'okay',2),
        (8, 0005, 2, 'okay',1),
        (8, 0012, 3, 'okay',2),
        (8, 0015, 2, 'okay',1),
        (8, 0007, 5, 'favorite',7),
        (8, 0005, 2, 'okay',1),
        (8, 0002, 4, 'delicious',4),
        (8, 0009, 2, 'okay',1),
        (9, 0013, 2, 'okay',1),
        (9, 0002, 3, 'okay',2),
        (9, 0003, 5, 'okay',6),
        (9, 0010, 3, 'okay',2),
        (9, 0001, 2, 'okay',1),
        (9, 0004, 4, 'okay',5),
        (9, 0007, 2, 'okay',1),
        (9, 0011, 3, 'okay',2),
        (9, 0016, 5, 'okay',4);

INSERT INTO pricing ( name, description, price )
  VALUES ('Iced Coffee 16oz','', 4.00),
        ('Iced Coffee 20oz','', 6.00),
        ('Shake or Smoothie 16oz','', 6.00),
        ('Shake or SMoothie 20oz','', 8.00),
        ('Shake, Tea, and Aloe','', 8.00),
        ('Shake and Coffee','', 9.00),
        ('Shake, Coffee with Aloe or Tea','', 10.00),
        ('Shake and Lifted Tea','', 11.00),
        ('add Extra Protein','', 2.00),
        ('add Collagen','Strawberry Lemonade', 3.00),
        ('add Fiber', 'Apple or Unflavored', 2.00),
        ('add Immunity Booster', '', 3.00),
        ('add Probiotic', '', 2.00),
        ('add Prolessa', 'Fat Reducer and Hunger Supressant', 4.00),
        ('Apple Bomb', 'Fat Blaster with added Fiber', 6.00),
        ('Donut Shot (Fat Blaster Shot)', 'Glazed Donut, Banana Cream, Cinnamon Roll, Lemon Tart', 5.00),
        ('Pre Workout', 'Mango or Watermelon', 5.00),
        ('Post Workout Shake', 'Chocolate, Vanilla Ice Cream, Strawberry Shortcake', 6.00);
